// Copyright Epic Games, Inc. All Rights Reserved.

#include "Interactable.h"

// BlueprintNativeEvent functions are auto-generated by UHT via GENERATED_BODY()
// Implementing classes should override the _Implementation functions
